# Generated by Django 3.2.5 on 2021-07-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210716_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
