# Generated by Django 3.2.5 on 2021-07-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210716_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowUser',
        ),
    ]
